// Path: tests/unit/symbol-bitmap-regenerate.test.js

/**
 * The map-free regenerator, which the `.ebgeo` import and the KMZ export both go
 * through.
 *
 * The failure it exists to prevent is SILENT. `generateSymbolBlob` throws
 * "Point ECHELON not found in catalog" when handed the echelon SCREEN code instead
 * of a real catalog code, and every caller of this module swallows the throw by
 * design (an application that will not start is worse than one stale bitmap). So an
 * unresolved code would show up as nothing at all: no error, no log the user sees,
 * just every echelon measure keeping its old oversized box forever.
 *
 * DIVERGE DA `main`: lá o módulo carregava a própria tabela de apelidos e a exportava
 * como `resolveMeasurePointCode`. Aqui quem resolve é `resolveDrawablePointCode`, que
 * já morava no catálogo desde o Núcleo (2026-09-03) e é a régua de
 * `frontend/tests/unit/kmz-nucleo-codigo-desenhavel.test.js`; uma segunda tabela seria
 * uma cópia dela, livre para divergir. Estes casos, portanto, atravessam o catálogo DE
 * VERDADE (o módulo o carrega por `import()` dinâmico, para não arrastá-lo ao chunk
 * `core`), e é isso que os torna mais fortes que os da `main`: eles medem a resolução
 * que roda em produção, não uma tabela dublê.
 *
 * The generators need the DOM and the milsymbol bundle, so they are injected here.
 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import {
    regenerateSymbolBitmap,
    isStaleBitmapFeature,
} from '@js/military_tools/symbol-bitmap.regenerate.js';
import { SYMBOL_BITMAP_VERSION } from '@layers/bitmap-version.js';

afterEach(() => {
    vi.restoreAllMocks();
});

describe('regenerateSymbolBitmap', () => {
    const RESULT = { blob: 'png', width: 78, height: 53 };

    it('returns the military generator result unchanged', async () => {
        const military = vi.fn().mockResolvedValue(RESULT);

        const result = await regenerateSymbolBitmap('military_symbol', { sidc: 'x' }, { military });

        expect(result).toBe(RESULT);
        expect(military).toHaveBeenCalledWith({ sidc: 'x' });
    });

    it('resolves the screen code BEFORE calling the measure generator', async () => {
        const measure = vi.fn().mockResolvedValue(RESULT);

        await regenerateSymbolBitmap(
            'coordination_measure',
            { pointCode: 'ECHELON', echelonCode: 'ECHELON_11', fillColor: '#fff' },
            { measure },
        );

        expect(measure).toHaveBeenCalledWith({
            pointCode: 'ECHELON_11',
            echelonCode: 'ECHELON_11',
            fillColor: '#fff',
        });
    });

    it('falls back to the default echelon when the feature never chose one', async () => {
        // Same defaults the tool control uses, so a feature regenerated by the import
        // cannot come out different from one regenerated by the panel.
        const measure = vi.fn().mockResolvedValue(RESULT);

        await regenerateSymbolBitmap('coordination_measure', { pointCode: 'ECHELON' }, { measure });
        expect(measure.mock.calls[0][0].pointCode).toBe('ECHELON_16');

        await regenerateSymbolBitmap('coordination_measure', { pointCode: 'ECHELON_FT' }, { measure });
        expect(measure.mock.calls[1][0].pointCode).toBe('ECHELON_FT_16');
    });

    it('leaves a real catalog code untouched, echelonCode or not', async () => {
        const measure = vi.fn().mockResolvedValue(RESULT);

        // A leftover echelonCode must NOT hijack a point that is not a screen code.
        await regenerateSymbolBitmap(
            'coordination_measure',
            { pointCode: '130100', echelonCode: 'ECHELON_11' },
            { measure },
        );

        expect(measure.mock.calls[0][0].pointCode).toBe('130100');
    });

    it('does not mutate the properties it was handed', async () => {
        const properties = { pointCode: 'ECHELON', echelonCode: 'ECHELON_11' };
        await regenerateSymbolBitmap('coordination_measure', properties, {
            measure: vi.fn().mockResolvedValue(RESULT),
        });

        // The screen code stays on the feature: it is what the panel shows.
        expect(properties.pointCode).toBe('ECHELON');
    });

    it('returns null and warns when the generator throws', async () => {
        const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
        const measure = vi.fn().mockRejectedValue(new Error('Point X not found in catalog'));

        await expect(
            regenerateSymbolBitmap('coordination_measure', { pointCode: 'X' }, { measure })
        ).resolves.toBeNull();
        expect(warn).toHaveBeenCalled();
    });

    it('returns null for a type that has no bitmap, without calling anything', async () => {
        const military = vi.fn();
        const measure = vi.fn();

        for (const type of ['point', 'polygon', 'magnetic_declination', undefined, null]) {
            await expect(regenerateSymbolBitmap(type, {}, { military, measure }))
                .resolves.toBeNull();
        }
        expect(military).not.toHaveBeenCalled();
        expect(measure).not.toHaveBeenCalled();
    });

    it('turns an empty generator answer into null', async () => {
        // `undefined` from a generator must not reach the caller as a truthy result.
        await expect(
            regenerateSymbolBitmap('military_symbol', {}, { military: async () => undefined })
        ).resolves.toBeNull();
    });

    it('WORST CASE: degenerate properties do not throw', async () => {
        const measure = vi.fn().mockResolvedValue(RESULT);

        await expect(regenerateSymbolBitmap('coordination_measure', undefined, { measure }))
            .resolves.toBe(RESULT);
        expect(measure.mock.calls[0][0].pointCode).toBeUndefined();

        // An empty echelonCode is not a code: the default has to win.
        await regenerateSymbolBitmap(
            'coordination_measure',
            { pointCode: 'ECHELON', echelonCode: '' },
            { measure },
        );
        expect(measure.mock.calls[1][0].pointCode).toBe('ECHELON_16');
    });
});

describe('isStaleBitmapFeature', () => {
    it('is true only for the two bitmap types without the current stamp', () => {
        expect(isStaleBitmapFeature('military_symbol', {})).toBe(true);
        expect(isStaleBitmapFeature('coordination_measure', { bitmapVersion: 1 })).toBe(true);
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: SYMBOL_BITMAP_VERSION }))
            .toBe(false);
    });

    it('never claims a type that has no versioned bitmap', () => {
        for (const type of ['point', 'image', 'magnetic_declination', 'polygon']) {
            expect(isStaleBitmapFeature(type, {}), type).toBe(false);
        }
    });

    it('WORST CASE: a stamp of the wrong shape counts as stale', () => {
        // `'2' === 2` is false, and that is the point: a string stamp means the
        // properties came from somewhere that did not use applyGeneratedBitmap.
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: String(SYMBOL_BITMAP_VERSION) }))
            .toBe(true);
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: NaN })).toBe(true);
        expect(isStaleBitmapFeature('military_symbol', undefined)).toBe(true);
    });
});
