-- Path: src/database/migrations/011_sv360_targets_target_id_index.sql
-- Índice em sv360.targets(target_id) — o lado NÃO-LÍDER da FK em cascata.
--
-- O PROBLEMA (medido, não suposto): sv360.targets tem DUAS FKs para
-- sv360.photos(id), ambas ON DELETE CASCADE:
--     targets_source_id_fkey (source_id)  -- coberta: PK (source_id, target_id)
--     targets_target_id_fkey (target_id)  -- NÃO coberta por índice nenhum
-- O Postgres não cria índice para a coluna REFERENCIANTE de uma FK. Então cada
-- linha removida de sv360.photos força um SEQ SCAN completo em sv360.targets para
-- achar as linhas em cascata por target_id.
--
-- Isso não é micro-otimização: o merge de um projeto é PURGE + REINSERT ("último
-- upload manda"), então toda REINGESTÃO paga esse custo. No corpus real
-- (624.003 targets), reimportar o projeto `alegrete` (16.794 fotos) significa
-- ~10^10 comparações — o DELETE ficou preso por mais de dez minutos num único
-- projeto e teve de ser abortado. Vale igual para o upload admin, não só para o
-- ETL offline: é o mesmo mergeProject.
--
-- PURGE_PROJECT_TARGETS (`WHERE source_id IN (...) OR target_id IN (...)`) usa o
-- mesmo índice no ramo do OR que hoje varre.
--
-- Sem `WHERE hidden = false`, ao contrário de idx_sv360_targets_source: um índice
-- PARCIAL não serve para a verificação de FK, que precisa enxergar toda linha
-- referenciante, inclusive as ocultas.

CREATE INDEX IF NOT EXISTS idx_sv360_targets_target_id ON sv360.targets(target_id);
