-- Path: src/database/migrations/015_remove_seeded_tileset.sql
-- O catálogo não promete tileset nenhum: tileset é configurado, não semeado.
--
-- O QUE ESTA MIGRAÇÃO REMOVE. A migração 003 inseria um tileset de demonstração,
-- `PCL` (Posto de Comando Logístico), apontando para `/3d/PCL/tileset.json` e um
-- `previewVideo` em `/3d/videos/preview.webm`.
--
-- POR QUE ELE NÃO PODIA FICAR. O asset NUNCA esteve no repositório: `public/3d/`
-- é ignorado pelo versionamento e só tinha dois `.gitkeep`. Ou seja, toda
-- instalação limpa sempre teve o catálogo prometendo um modelo que o servidor
-- não serve. O sintoma é silencioso do jeito ruim: o item aparece listado e
-- clicável no mapa 2D, e abrir o visualizador 3D dá 404, que o `openViewer`
-- captura e devolve para o 2D sem dizer nada. O mesmo registro já apontava para
-- um `thumbnail.jpg` que jamais existiu, o que mostra há quanto tempo a promessa
-- estava vencida.
--
-- Isto é MIGRAÇÃO, e não seed de desenvolvimento: `seed.js` é opcional, migração
-- roda em todo ambiente, inclusive produção. Por isso o registro não podia ser
-- apagado editando a 003, que já rodou em bancos existentes. Aqui vale a regra
-- forward-only da casa, e a remoção é aditiva no sentido que importa: ela
-- desfaz um dado, não uma estrutura.
--
-- A DECISÃO, do dono do produto: o catálogo é ponto de configuração, não lugar
-- de conteúdo de exemplo. Um tileset entra pelo Painel do Administrador, ou pelo
-- import de acervo 3D, apontando para uma URL que existe. Semear conteúdo numa
-- migração faz o dado nascer errado em toda instalação nova e obriga cada
-- deployment a limpar o que nunca pediu.
--
-- SEM EFEITO COLATERAL DE INTEGRIDADE: não existe chave estrangeira para
-- `tilesets`. As tabelas de 3D guardam `tileset_id` como texto livre, então
-- marcador e medição de um tileset removido continuam existindo e apenas deixam
-- de ter o registro de catálogo correspondente, que é o mesmo estado de quem
-- nunca teve o seed.
--
-- Idempotente: o DELETE não falha se a linha já não estiver lá (banco novo, ou
-- alguém que já a tenha removido pelo painel).

DELETE FROM tilesets WHERE id = 'PCL';
