// Path: tests/helpers/ebgeo-fixture.js

/**
 * @fileoverview Turns a REAL `.ebgeo` produced by the `main` app into the IndexedDB state a
 * schema-2.2 user actually has on disk, so the 2.2 to 2.3 migration can be run against
 * production data instead of against a hand-built mock of it.
 *
 * WHERE THE FILES COME FROM. `tests/fixtures/ebgeo-2.2/*.ebgeo` are byte-for-byte copies of
 * `_ebgeo_dados_teste/` (sha256 verified at copy time), which were generated by driving the
 * `main` app with Playwright and exporting through the production export path. Nothing here
 * edits them, and nothing here writes a `.ebgeo`: hand-writing that archive would test the
 * migration against the test author's reading of the format instead of against the format.
 *
 * HOW IT IS READ, and the trap that costs an hour: the archive is a ZIP masked by XOR 0xAA
 * behind a six-byte `EBGXOR` header, and `fflate` REFUSES the ZIP that JSZip writes. So this
 * file uses JSZip, which is the very library `export-import.service.js` uses, is already a
 * dependency, and works unchanged in node. No conversion step, no derived JSON copy, no
 * second reading of the format.
 *
 * WHAT THE SEEDER IS AND IS NOT. `seedLegacyWorkspace` writes the PRE-NAMESPACE databases
 * (`ebgeo_maps`, `ebgeo_layers`, ...) directly through localforage, mirroring the key layout
 * of `src/js/store/repositories/local.repository.js` (`layers_<map>`, `groups` keyed by map
 * name, `cesium3d_<map>`, `temporal_<map>`, briefings keyed by id, images keyed by id). It
 * is NOT the `.ebgeo` import path: that path pulls in the whole `@store` barrel and modal
 * UI and cannot run in node. Because a hand-written layout is exactly the kind of copy that
 * drifts and then certifies the drift, every test that seeds through this helper is required
 * to read the result back through the REAL repository (`localRepository`) as well as by
 * absolute database name. If the layout were wrong, the repository read would come back
 * empty while the raw read came back full, and the two would disagree out loud.
 *
 * ---------------------------------------------------------------------------
 * THE ARCHIVE IS NOT THE DISK RECORD, AND PRETENDING OTHERWISE WAS WRONG
 * ---------------------------------------------------------------------------
 * An earlier version of this file said the archive holds "the stored record minus `id`,
 * `name` and `sync`". It does not. `exportProject` REBUILDS each map payload from separate
 * accessors (`ebgeo_web_main/src/js/import_export/export-import.service.js`, the
 * `fullMapData` literal): `hillshadeEnabled: true` and `analysisLayers: {}` are HARDCODED
 * there, and `baseLayer`, `zoom`, `center_lat`, `center_long`, `bearing` and `pitch` come
 * from `getCurrentBaseLayer`/`getMapPosition`, not from the record in `ebgeo_maps`. So what
 * is seeded here is a FAITHFUL REPLAY OF THE EXPORT, and a test built on it proves the
 * migration survives that shape, not that it survives every field a user's disk may carry.
 * Where the difference is knowable it is closed: `main` writes `id: <resolved map key>`
 * (`local.repository.js`, `saveMap`), so `mapRecord` writes the map name, not `null`.
 *
 * WHAT THE ARCHIVE DOES NOT CARRY AT ALL, and is therefore fabricated or omitted here:
 *   - `mapOrder` lives in `ebgeo_app_settings['mapOrder']` on disk (`main`'s
 *     `map.operations.js` via `getSettingCompat`) and in `data.mapOrder` in the archive.
 *     It is written to BOTH homes below, so a test can assert the order survives.
 *   - the ACTIVE LAYER per map (`activeLayer_<map>`) is not exported. It is NOT invented
 *     here: absence is the faithful answer, and `getLayers`/`getActiveLayer` already fall
 *     back. Writing `'default'` for a map with seven layers, one of them renamed, would be
 *     a value no user has.
 *   - `ebgeo_comments` DOES NOT EXIST in `main` (nine stores, listed at the top of its
 *     `local.repository.js`; spatial comments were born on `integracao_backend`). Seeding
 *     it would give the "2.2 install" a database no real 2.2 user has, and any future gate
 *     that decides by database EXISTENCE would be answered by the instrument.
 *     `LEGACY_STORE_IDS` below is the closed list of the nine, and `seedLegacyWorkspace`
 *     touches nothing outside it.
 *
 * IMAGE BLOBS: `main` stores a `Blob`, this seeder stores whatever `IMAGE_VALUE_FORM` says
 * the runtime can hold. Under node + `fake-indexeddb` that is raw bytes, for the measured
 * reason written at that constant. It is DECLARED and asserted, never silent.
 *
 * Database NAMES are never built here. They come from `resolveDbName()` in
 * `src/js/store/atlas-namespace.js`, for the reason stated in `idb-helpers.js`.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import JSZip from 'jszip';
import { seedDatabase } from './idb-helpers.js';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Directory holding the schema-2.2 archives. */
const FIXTURE_DIR = join(HERE, '..', 'fixtures', 'ebgeo-2.2');

/** Mask byte the exporter XORs the ZIP with. */
const XOR_KEY = 0xAA;

/** Magic prefix the exporter puts in front of the masked ZIP. */
const MASK_HEADER = 'EBGXOR';

/**
 * The NINE pre-namespace databases `main` creates, as `StoreName` values.
 *
 * Closed on purpose, and `comments` is absent on purpose: see the fileoverview. A caller
 * passing a `names` map with more entries (this branch's `StoreName` has ten per-atlas
 * stores) still gets exactly these nine touched.
 */
export const LEGACY_STORE_IDS = Object.freeze([
    'atlas', 'maps', 'images', 'settings', 'groups',
    'layers', 'cesium3d', 'streetview360', 'briefings'
]);

/**
 * Which form image values take in the seeded databases, DECLARED rather than assumed.
 *
 * `main` stores a `Blob` (`local.repository.js`, `saveImage`). Storing one here needs more
 * than the `Blob` constructor: localforage's IndexedDB driver decides blobs are unsupported
 * under `fake-indexeddb` and falls back to `_encodeBlob`, which uses `FileReader` — and node
 * has no global `FileReader`, so the write throws. MEASURED: `new Blob(...)` alone turns ten
 * cases of the migration harness red with `ReferenceError: FileReader is not defined`.
 *
 * So the form is conditional and NAMED. A test asserts this value, which is what keeps the
 * limitation from being silent: the day the environment can hold a real `Blob`, the assertion
 * flips and someone reads this paragraph instead of rediscovering it.
 *
 * WHAT IT COSTS while it is `'bytes'`: nothing that reads a blob's `.type` (the exporter's
 * `getBlobExtension` does) can be exercised through this seeder. Presence and count can.
 * @type {'blob'|'bytes'}
 */
export const IMAGE_VALUE_FORM =
    typeof Blob === 'function' && typeof FileReader === 'function' ? 'blob' : 'bytes';

/**
 * Wraps image bytes the way the app stores them, when the runtime allows it.
 * @param {Uint8Array} bytes - Raw PNG bytes from the archive.
 * @returns {Blob|Uint8Array} See `IMAGE_VALUE_FORM`.
 */
function asImageBlob(bytes) {
    return IMAGE_VALUE_FORM === 'blob' ? new Blob([bytes], { type: 'image/png' }) : bytes;
}

/**
 * Reads and unmasks one archive.
 * @param {string} fileName - File inside `tests/fixtures/ebgeo-2.2/`.
 * @returns {Promise<{ data: Object, images: Map<string, Uint8Array> }>} The parsed
 *   `data.json` and every blob under `images/`, keyed by the image id (the file stem).
 */
export async function loadEbgeoFixture(fileName) {
    const raw = new Uint8Array(readFileSync(join(FIXTURE_DIR, fileName)));

    const header = new TextDecoder().decode(raw.slice(0, MASK_HEADER.length));
    const masked = header === MASK_HEADER ? raw.slice(MASK_HEADER.length) : raw;
    const zipBytes = header === MASK_HEADER
        ? Uint8Array.from(masked, byte => byte ^ XOR_KEY)
        : masked;

    const zip = await JSZip.loadAsync(zipBytes);

    const dataFile = zip.file('data.json');
    if (!dataFile) {
        throw new Error(`ebgeo-fixture: ${fileName} has no data.json`);
    }
    const data = JSON.parse(await dataFile.async('string'));

    const images = new Map();
    for (const entry of zip.file(/^images\/.+/)) {
        const id = entry.name.replace(/^images\//, '').replace(/\.[^.]+$/, '');
        images.set(id, await entry.async('uint8array'));
    }

    return { data, images };
}

/**
 * Counts what the archive DECLARES, so a test can compare against the numbers the fixture
 * README states instead of against whatever the code under test happened to produce.
 *
 * @param {{ data: Object, images: Map<string, Uint8Array> }} fixture - Loaded archive.
 * @returns {{ schemaVersion: string, maps: number, features: number, featuresByMap: Object,
 *   layers: number, groups: number, briefings: number, slides: number, customIcons: number,
 *   images: number, mapNames: string[] }}
 */
export function countFixture({ data, images }) {
    const featuresByMap = {};
    let features = 0;
    for (const [mapName, mapData] of Object.entries(data.maps ?? {})) {
        let count = 0;
        for (const list of Object.values(mapData.features ?? {})) {
            if (Array.isArray(list)) count += list.length;
        }
        featuresByMap[mapName] = count;
        features += count;
    }

    let layers = 0;
    for (const list of Object.values(data.layers ?? {})) {
        if (Array.isArray(list)) layers += list.length;
    }

    let groups = 0;
    for (const byId of Object.values(data.groups ?? {})) {
        groups += Object.keys(byId ?? {}).length;
    }

    const briefings = Array.isArray(data.briefings) ? data.briefings : [];
    const slides = briefings.reduce((sum, b) => sum + (b.slides?.length ?? 0), 0);

    return {
        schemaVersion: data.version,
        maps: Object.keys(data.maps ?? {}).length,
        features,
        featuresByMap,
        layers,
        groups,
        briefings: briefings.length,
        slides,
        customIcons: (data.customIcons ?? []).length,
        images: images.size,
        mapNames: Object.keys(data.maps ?? {})
    };
}

/**
 * Builds the record `ebgeo_maps` holds for one map.
 *
 * The archive stores a REBUILT map payload (`optimizeMapData` over the `fullMapData`
 * literal), not the record on disk: see the fileoverview for which fields the exporter
 * invents. What is restored here is the envelope `local.repository.js` writes around it,
 * and `id` is the RESOLVED MAP KEY — for a name-keyed local store that is the map name,
 * never `null`, which is what `main`'s `saveMap` puts there.
 *
 * @param {string} mapName - Map name (also the key).
 * @param {Object} mapData - Exported map payload.
 * @param {number} now - Epoch ms for the sync metadata.
 * @returns {Object} Stored map record.
 */
function mapRecord(mapName, mapData, now) {
    return {
        id: mapName,
        name: mapName,
        sync: { createdAt: now, updatedAt: now, version: 1, ownerId: null, dirty: true, deleted: false, deletedAt: null },
        ...mapData
    };
}

/**
 * The absolute names of the nine databases `seedLegacyWorkspace` touches, sorted.
 *
 * A test asserts `listDatabases()` against this right after seeding, which is what turns
 * "the instrument creates exactly the nine `main` has" from a comment into a check.
 * @param {Object<string, string>} names - Absolute names keyed by `StoreName` value.
 * @returns {string[]}
 */
export function legacyDbNames(names) {
    return LEGACY_STORE_IDS.map(id => names[id]).sort();
}

/**
 * Turns one loaded archive into the KEY/VALUE CONTENT of each pre-namespace database.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS SEPARATE FROM THE WRITING
 * ---------------------------------------------------------------------------
 * The key layout below (`layers_<map>`, `cesium3d_<map>`, briefings by id, `custom_icons`,
 * `mapOrder` in two homes) is a hand-mirror of `local.repository.js`, and the fileoverview
 * explains why every test that uses it must read back through the real repository. There is
 * now a SECOND consumer that cannot call `seedDatabase`: `tests/e2e-ui/browser-migracao-2.2.spec.js`
 * seeds inside a Chromium page, where the writing has to happen through the app's own
 * `getStoreFor` and the node-side `localforage` is not in reach.
 *
 * Two copies of this layout would drift, and the drift would be invisible: the node harness
 * would keep passing on the old shape while the browser one seeded a repository no user has.
 * So the layout is built ONCE, here, as plain data, and each caller writes it its own way.
 *
 * The result is keyed by `StoreName` VALUE (`maps`, `layers`, ...), never by database name:
 * names come from `resolveDbName()`, and this file builds none.
 *
 * @param {{ data: Object, images: Map<string, Uint8Array> }} fixture - Loaded archive.
 * @param {Object} [options]
 * @param {string} [options.schemaVersion='2.2'] - Version stamp to write.
 * @param {string} [options.atlasName='Meu Atlas'] - Name of the seeded atlas record.
 * @param {string} [options.atlasId] - Id of the seeded atlas record.
 * @param {(bytes: Uint8Array) => *} [options.imageValue] - How to wrap image bytes. Defaults
 *   to `IMAGE_VALUE_FORM`; the browser seeder overrides it because a `Uint8Array` does not
 *   survive the trip into a page and a real browser can hold a real `Blob`.
 * @param {number} [options.now] - Epoch ms for the sync metadata.
 * @returns {Object<string, Object<string, *>>} Entries per `StoreName` value.
 */
export function buildLegacyEntries(fixture, {
    schemaVersion = '2.2',
    atlasName = 'Meu Atlas',
    atlasId = 'seeded-atlas',
    imageValue = asImageBlob,
    now = Date.now()
} = {}) {
    const { data, images } = fixture;

    const maps = {};
    for (const [mapName, mapData] of Object.entries(data.maps ?? {})) {
        maps[mapName] = mapRecord(mapName, mapData, now);
    }

    // `mapOrder` has TWO homes and the archive only shows one of them. `main` reads it from
    // the settings database (`getSettingCompat('mapOrder')`); the atlas record below carries
    // its own copy. Writing only the second is how an earlier version of this seeder made
    // "the order survived" and "the order was never seeded" the same green.
    const settings = { schemaVersion, lastActiveMap: data.currentMap };
    if (Array.isArray(data.mapOrder)) settings.mapOrder = [...data.mapOrder];
    for (const [mapName, notes] of Object.entries(data.mapNotes ?? {})) {
        settings[`map_notes_${mapName}`] = notes;
    }
    for (const [mapName, usage] of Object.entries(data.colorUsage ?? {})) {
        settings[`color_usage_${mapName}`] = usage;
    }
    for (const [mapName, style] of Object.entries(data.gridStyle ?? {})) {
        settings[`gridStyle_${mapName}`] = style;
    }
    for (const [mapName, temporal] of Object.entries(data.temporal ?? {})) {
        settings[`temporal_${mapName}`] = temporal;
    }
    if ((data.customIcons ?? []).length > 0) {
        settings.custom_icons = data.customIcons;
    }

    const layers = {};
    for (const [mapName, list] of Object.entries(data.layers ?? {})) {
        layers[`layers_${mapName}`] = list;
        // No `activeLayer_<map>`: the archive does not export it, and inventing 'default'
        // for a map with seven layers writes a value no user has. Absence is faithful.
    }

    const cesium3d = {};
    for (const [mapName, value] of Object.entries(data.cesium3d ?? {})) {
        cesium3d[`cesium3d_${mapName}`] = value;
    }

    const streetview360 = {};
    for (const [mapName, value] of Object.entries(data.streetview360 ?? {})) {
        streetview360[`streetview360_${mapName}`] = value;
    }

    const briefings = {};
    for (const briefing of data.briefings ?? []) {
        briefings[briefing.id] = briefing;
    }

    const imageEntries = {};
    for (const [id, bytes] of images) {
        imageEntries[id] = imageValue(bytes);
    }

    // NO `ebgeo_comments`: `main` has nine stores and none of them is comments. Creating it
    // here would hand every existence-based gate a database no 2.2 user has.
    return {
        maps,
        settings,
        layers,
        groups: { ...(data.groups ?? {}) },
        cesium3d,
        streetview360,
        briefings,
        images: imageEntries,
        atlas: {
            current_atlas: {
                id: atlasId,
                name: atlasName,
                sync: { createdAt: now, updatedAt: now, version: 1, ownerId: null, dirty: true, deleted: false, deletedAt: null },
                schemaVersion,
                mapOrder: data.mapOrder ?? [],
                lastActiveMapId: null,
                settings: { terrainExaggeration: 1.5 }
            }
        }
    };
}

/**
 * Writes one loaded archive into the PRE-NAMESPACE databases, at the given schema version.
 *
 * @param {{ data: Object, images: Map<string, Uint8Array> }} fixture - Loaded archive.
 * @param {Object} names - Absolute database names, keyed by `StoreName` value. Built by the
 *   caller with `resolveDbName()` so no naming rule is reimplemented here.
 * @param {Object} [options] - See `buildLegacyEntries`.
 * @returns {Promise<void>}
 */
export async function seedLegacyWorkspace(fixture, names, options = {}) {
    const byStore = buildLegacyEntries(fixture, options);
    for (const storeId of LEGACY_STORE_IDS) {
        await seedDatabase(names[storeId], byStore[storeId]);
    }
}
