// Path: tests/unit/symbol-bitmap-regenerate.test.js

/**
 * The map-free regenerator, which the migration, the `.ebgeo` import and the KMZ
 * export all go through.
 *
 * The failure it exists to prevent is SILENT. `generateSymbolBlob` throws
 * "Point ECHELON not found in catalog" when handed the echelon ALIAS instead of a
 * real catalog code, and every caller of this module swallows the throw by design
 * (an application that will not start is worse than one stale bitmap). So an
 * unresolved alias would show up as nothing at all: no error, no log the user sees,
 * just every echelon measure keeping its old oversized box forever.
 *
 * The generators need the DOM and the `ms` global, so they are injected here.
 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import {
    resolveMeasurePointCode,
    regenerateSymbolBitmap,
    isStaleBitmapFeature,
} from '@js/military_tools/symbol-bitmap.regenerate.js';
import { SYMBOL_BITMAP_VERSION } from '@js/military_tools/bitmap-version.js';

afterEach(() => {
    vi.restoreAllMocks();
});

describe('resolveMeasurePointCode', () => {
    it('resolves the two echelon aliases to the chosen echelon code', () => {
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON', echelonCode: 'ECHELON_11' }))
            .toBe('ECHELON_11');
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON_FT', echelonCode: 'ECHELON_FT_13' }))
            .toBe('ECHELON_FT_13');
    });

    it('falls back to the default echelon when the feature never chose one', () => {
        // Same defaults the tool control uses, so a feature regenerated by the
        // migration cannot come out different from one regenerated by the panel.
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON' })).toBe('ECHELON_16');
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON_FT' })).toBe('ECHELON_FT_16');
    });

    it('leaves a real catalog code untouched, echelonCode or not', () => {
        expect(resolveMeasurePointCode({ pointCode: '130100' })).toBe('130100');
        // A leftover echelonCode must NOT hijack a point that is not an alias.
        expect(resolveMeasurePointCode({ pointCode: '130100', echelonCode: 'ECHELON_11' }))
            .toBe('130100');
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON_16' })).toBe('ECHELON_16');
    });

    it('WORST CASE: degenerate input does not throw', () => {
        expect(() => resolveMeasurePointCode(undefined)).not.toThrow();
        expect(resolveMeasurePointCode(undefined)).toBeUndefined();
        expect(resolveMeasurePointCode(null)).toBeUndefined();
        expect(resolveMeasurePointCode({})).toBeUndefined();
        // An empty echelonCode is not a code: the default has to win.
        expect(resolveMeasurePointCode({ pointCode: 'ECHELON', echelonCode: '' }))
            .toBe('ECHELON_16');
    });
});

describe('regenerateSymbolBitmap', () => {
    const RESULT = { blob: 'png', width: 78, height: 53 };

    it('returns the military generator result unchanged', async () => {
        const military = vi.fn().mockResolvedValue(RESULT);

        const result = await regenerateSymbolBitmap('military_symbol', { sidc: 'x' }, { military });

        expect(result).toBe(RESULT);
        expect(military).toHaveBeenCalledWith({ sidc: 'x' });
    });

    it('resolves the alias BEFORE calling the measure generator', async () => {
        const measure = vi.fn().mockResolvedValue(RESULT);

        await regenerateSymbolBitmap(
            'coordination_measure',
            { pointCode: 'ECHELON', echelonCode: 'ECHELON_11', fillColor: '#fff' },
            { measure },
        );

        expect(measure).toHaveBeenCalledWith({
            pointCode: 'ECHELON_11',
            echelonCode: 'ECHELON_11',
            fillColor: '#fff',
        });
    });

    it('does not mutate the properties it was handed', async () => {
        const properties = { pointCode: 'ECHELON', echelonCode: 'ECHELON_11' };
        await regenerateSymbolBitmap('coordination_measure', properties, {
            measure: vi.fn().mockResolvedValue(RESULT),
        });

        // The alias stays on the feature: it is what the panel shows.
        expect(properties.pointCode).toBe('ECHELON');
    });

    it('returns null and warns when the generator throws', async () => {
        const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
        const measure = vi.fn().mockRejectedValue(new Error('Point X not found in catalog'));

        await expect(
            regenerateSymbolBitmap('coordination_measure', { pointCode: 'X' }, { measure })
        ).resolves.toBeNull();
        expect(warn).toHaveBeenCalled();
    });

    it('returns null for a type that has no bitmap, without calling anything', async () => {
        const military = vi.fn();
        const measure = vi.fn();

        for (const type of ['point', 'polygon', 'magnetic_declination', undefined, null]) {
            await expect(regenerateSymbolBitmap(type, {}, { military, measure }))
                .resolves.toBeNull();
        }
        expect(military).not.toHaveBeenCalled();
        expect(measure).not.toHaveBeenCalled();
    });

    it('turns an empty generator answer into null', async () => {
        // `undefined` from a generator must not reach the caller as a truthy result.
        await expect(
            regenerateSymbolBitmap('military_symbol', {}, { military: async () => undefined })
        ).resolves.toBeNull();
    });
});

describe('isStaleBitmapFeature', () => {
    it('is true only for the two bitmap types without the current stamp', () => {
        expect(isStaleBitmapFeature('military_symbol', {})).toBe(true);
        expect(isStaleBitmapFeature('coordination_measure', { bitmapVersion: 1 })).toBe(true);
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: SYMBOL_BITMAP_VERSION }))
            .toBe(false);
    });

    it('never claims a type that has no versioned bitmap', () => {
        for (const type of ['point', 'image', 'magnetic_declination', 'polygon']) {
            expect(isStaleBitmapFeature(type, {}), type).toBe(false);
        }
    });

    it('WORST CASE: a stamp of the wrong shape counts as stale', () => {
        // `'2' === 2` is false, and that is the point: a string stamp means the
        // properties came from somewhere that did not use applyGeneratedBitmap.
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: String(SYMBOL_BITMAP_VERSION) }))
            .toBe(true);
        expect(isStaleBitmapFeature('military_symbol', { bitmapVersion: NaN })).toBe(true);
        expect(isStaleBitmapFeature('military_symbol', undefined)).toBe(true);
    });
});
